[package]
name = "rust-noodles"
version = "0.1.0"
edition = "2021"

[dependencies]
noodles = { version = "0.14.0", features = ["bcf", "vcf"] }
noodles-bgzf = { version = "0.7.0", features = ["libdeflate"] }
