[package]
name = "rust-rhtslib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = { version = "*", path="/home/brentp/src/rust-htslib/" }
